Repository tprasadtp/protonvpn-docker, pull requests merged in 2023-05, with the labels that each got.

#219 fix: IPv6 checks when kernel module is not present
  protonwire
Labels: bugfix, luna/automerge

#220 docs: faq add info about wireguard support in kernel
  .github/ISSUE_TEMPLATE/bugreport.yml
  README.md
  docs/faq.md
Labels: documentation

#221 ci: replace use of set-output as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
  .github/workflows/security.yml
Labels: ci

#222 feat: use single route table for both kill-switch and VPN routing
  .editorconfig
  .github/ISSUE_TEMPLATE/bugreport.yml
  .github/ISSUE_TEMPLATE/metadata.yml
  Dockerfile
  README.md
  SECURITY.md
  Vagrantfile
  docs/examples/docker-compose-demo.yml
  docs/faq.md
  docs/help.md
  protonwire
Labels: enhancement

#224 metadata: allow lowercase server names
  .goreleaser.yml
  Vagrantfile
  scripts/generate-server-metadata
Labels: bugfix, metadata, api/metadata

#225 fix: disallow automatic server selection via country code
  docs/faq.md
  protonwire
Labels: bugfix

#226 chore: update gh issue forms
  .github/ISSUE_TEMPLATE/bugreport.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/metadata.yml
Labels: maintenance

#227 docs: add info about `PROTONVPN_SERVER` containing yaml comment char '#'
  README.md
  docs/examples/docker-compose-demo.yml
Labels: documentation

#231 docs: use v7 tag for template
  README.md
  docs/examples/container-protonwire.service
Labels: documentation, bugfix

#232 docs: prioritize compose file over docker/podman, use custom bridge network in examples
  README.md
  docs/examples/container-protonwire.service
Labels: documentation

#234 docs: skip using --cgroups=split as it results in systemd units enter…
  README.md
  docs/examples/container-protonwire-example-app.service
  docs/examples/container-protonwire.service
Labels: documentation, podman, systemd
